# http://localhost:8888/bacs
#?? ????
server:
  port: 8888
#Context Path
  servlet.context-path: /bacs
#Logback ??. ??? ???? ?? ?? ??

#error>warn>info>debug>trace
logging:
  level:
    root: debug # Temp

# ??? ?? ??
spring:
  profiles:
    active: prod # prod, dev(test), local

  config:
    import:
      - app/jwt/jwt.yml # classpath:/app/jwt/jwt.yml

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${db.url:jdbc:oracle:thin:@localhost:1521/xe} # ${????:???}
    username: ${db.username:hr}
    password: ${db.password:hr}

# MyBatis
mybatis:
  type-aliases-package: net.softsociety.bacs.domain
  mapper-locations: mappers/**/*.xml
